/vis/open OGL
/vis/drawVolume

/vis/viewer/set/viewpointThetaPhi 90 0
/vis/viewer/addCutawayPlane 0 0 0 cm 1 0 0
#/vis/viewer/set/sectionPlane on 0 0 0 cm 1 0 0
/vis/viewer/zoomTo 2
#/vis/viewer/set/background white
#/vis/viewer/set/lightsVector -0.8 1 0
#/vis/viewer/flush

/vis/scene/add/trajectories
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate 1000

# to output info on the volumes
#/vis/ASCIITree/verbose 5
#/vis/ASCIITree/set/outFile PoGOLite+VolumesInfo
#/vis/drawTree
